### ISSUE TITLE
Currency formatting issue

### ISSUE THREAD

**Issue by who** [kitbogashow/how-to-fix-paypal#16]
I noticed that the invoices.txt has currency formatted as `$479. 00 USD`. Notice the extra space between the period and the cents portion of the amount. Is this an intentional formatting change that the bad guys use to bypass filters, or is this an issue with the sample invoices?

**Comment by kitbogashow** [comment]
The formatting is directly copied from the email invoices in question. They may have been intentionally entered by the scammers or could be an accident.
