### ISSUE TITLE
Probable source of the email

### ISSUE THREAD

**Issue by SPorpora** [kitbogashow/how-to-fix-paypal#23]
https://developer.paypal.com/docs/api/invoicing/v2/

Might be the way the invoices are being generated. A key point to determine whether is a scam could be the IP/location of the api call, if it is from India or other famous scam states the possibility of being a scam must be higher.

Need a database of location of known scam call centers fed by accredited scambaiters, this way you can see if the ip is near a high concentration of call centers.

**Comment by magnus-rattlehead** [comment]
I think this plus an invoice filtering approach is the most effective way to stop these kinds of scams. Of course the scammers could use a VPN or some kind of "mule" to setup so they aren't filtered by location. I think any hurdle that they have to overcome to setup this scam can slow them down and hurt their bottom line is good.

**Comment by kitbogashow** [comment]
While I understand your thought process, I don't think the solution needs to be this complicated nor would focusing on "famous scam states" be appropriate. 
Scammers could easily use victims own computers and paypal accounts to send these emails (and likely already are) regardless of their personal location.
